import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import AuthProvider from "../../context/AuthProvider";
import Header from "./components/nav/Header";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora',
})

export const metadata: Metadata = {
  title: "write | where good ideas find you",
  description: "Generated by create next app",
  keywords:["Blogs", "NextJS", "vercel", "OpenSource"],
  icons: {
    icon:'/blob.ico',
  }

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/blob.ico" />
      </head>
      <body className={`${inter.className} ${lora.variable}`}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <AuthProvider>
        <div>
          <Header/>
        </div>
        <div className="mt-8">
          {children}
        </div>
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
